Feat/cloth list
team0102/weather-backend pull request #11
Opened 2024-02-05 09:52 UTC by jeongjin01

## Motivation 🎉
 - 기존의 WeatherEntity삭제 후 ClothEntity에 'lowPerceivedTemperature', 'highPerceivedTemperature' 추가

 - temperature를 받아서 lowPerceivedTemperature, highPerceivedTemperature의 범위 내에 있는 clothesSet을 출력

 - 회원가입(로그인)을 하지 않은 유저일 때 clothSets만 배열로 출력되고,
<img width="931" alt="스크린샷 2024-02-05 오후 6 45 04" src="https://github.com/team0102/weather-backend/assets/124764438/d8e25ba4-bf5b-4035-a268-c22cd0445ad3">

 - 회원가입(로그인)을 한 유저일 때 temperatureSensitivity가 출력되도록 함
<img width="931" alt="스크린샷 2024-02-05 오후 6 48 15" src="https://github.com/team0102/weather-backend/assets/124764438/814d5c7d-23e7-491c-9890-d292eb0511fd">

## Key Changes 🗝️
 - getClothesSetIdByWeather에서 존재하지 않는 토큰일 때 
   ＊ 
<img width="935" alt="스크린샷 2024-02-05 오후 6 50 26" src="https://github.com/team0102/weather-backend/assets/124764438/88098934-6899-4049-a0fe-be94714fabdf">

 - 범위 내에 해당하는 온도가 없을 때
   ＊ 
<img width="931" alt="스크린샷 2024-02-05 오후 6 51 39" src="https://github.com/team0102/weather-backend/assets/124764438/78b2c0e1-a29b-4336-aaf0-724184900da5">

2024-02-05 11:47 UTC, JISUlicious requested changes

2024-02-05 11:47 UTC, JISUlicious commented on src/entities/clothes.entity.ts
>    @OneToOne(() => ClothSetEntity)
OneToOne이면 clothes와 clotheSet을 합치는건 어떨까요?
둘이 딱히 분리될 필요가 없어보입니다.
지난번에 얘기 할 때도 둘 중 하나 없어도 될 것 같다고 이야기 했던 것 같아요

2024-02-05 11:47 UTC, JISUlicious commented on src/clothes/clothes.service.ts
> +      }
지난번에 프론트에서 보정된 체감온도 값으로 보내드리겠다고 했던 것 같습니다.
프론트에서 보정된 값을 보내려면 체감온도 계산 할 때 온도민감도 값이 필요하니까, 프론트에서 값을 이미 갖고있어야 할 것 같고요.
그러면 백엔드에서 따로 응답에 포함시킬 필요가 있을까요?

2024-02-07 08:40 UTC, Park-KJ requested changes

2024-02-07 08:40 UTC, Park-KJ commented on src/entities/clothes.entity.ts
>    @CreateDateColumn({
코드 정리해주시면 가독성에 좋을 듯 합니다.
column 관련 부분을 위로, 연관관계 관련 부분을 아래로 분리하는게 어떨까요?

2024-02-07 08:40 UTC, Park-KJ commented on src/clothes/clothes.service.ts
> +      await this.userRepository.findOneBy({ id: loginUserId });
별도의 repository를 생성해 함수를 불러온 것이 아닌 typeorm의 함수를 바로 사용한 것으로 보입니다.
형식 통일을 위해 repository 생성 후 함수를 불러와 사용하는 것으로 (나중에!) 수정하면 좋겠습니다.

2024-02-07 15:09 UTC, Park-KJ approved these changes

2024-02-07 15:37 UTC, Park-KJ approved these changes

2024-02-08 05:58 UTC, Park-KJ approved these changes

2024-02-08 05:58 UTC, jeongjin01 commented on src/entities/clothes.entity.ts
>    @OneToOne(() => ClothSetEntity)
넵 두 개를 합치는 방향으로 수정하겠습니다!

2024-02-08 05:58 UTC, jeongjin01 commented on src/clothes/clothes.service.ts
> +      }
로그인 한 유저가 온도 민감도를 체크하면 체크한게 유지되어야 할  것 같아서 응답에 포함시킨 것이었는데
응답 값에 포함시키는게 아니라 애초에 로그인을 할 때 토큰에 민감도 값을 추가하면 될까요??

2024-02-08 05:58 UTC, jeongjin01 commented on src/entities/clothes.entity.ts
>    @CreateDateColumn({
넵 수정하겠습니다!

2024-02-08 05:58 UTC, jeongjin01 commented on src/clothes/clothes.service.ts
> +      await this.userRepository.findOneBy({ id: loginUserId });
넵!

2024-02-08 05:58 UTC, Park-KJ approved these changes

2024-02-08 06:04 UTC, JISUlicious approved these changes

2024-02-08 06:07 UTC, merged