이미지를 파일로 받아 저장
team0102/weather-backend pull request #29
Opened 2024-02-22 10:56 UTC by heyw00

## Motivation 🎉
 - 이미지 파일을 경로에 저장하여 url로 반환하도록 수정
    ＊ form-data 
![image](https://github.com/team0102/weather-backend/assets/120547603/d2b779e6-6ac2-40fc-918b-18457807a8f2)

## Key Changes 🗝️
 - createFeed, updateFeed 시 이미지 파일을 받아 public 내 경로에 저장
   ＊ 유저 프로필 사진의 경우 public/users 에 저장하는 등 활용 가능
![image](https://github.com/team0102/weather-backend/assets/120547603/d2fce486-c41a-4e80-bf94-3ca590bfc792)

 - 피드 데이터에서는 /public/feeds/파일명 으로 응답
   
![image](https://github.com/team0102/weather-backend/assets/120547603/f4ab9999-d828-4d34-9758-f1fc07b72acb)
![image](https://github.com/team0102/weather-backend/assets/120547603/ae3b0d89-c630-484c-a46a-a9555a70c961)

 - 피드 수정 시 , 이미지 변경 유무와 상관없이 새로운 이미지를 경로에 저장하고, 기존 이미지를 삭제한다.

2024-02-22 12:13 UTC, jeongjin01 approved these changes

2024-02-22 12:18 UTC, JISUlicious requested changes

2024-02-22 12:18 UTC, JISUlicious commented on src/feed/feed.service.ts
> +            imageUrl : `/${FEED_PUBLIC_IMAGE_PATH}/${imageUrl}`,
image url 결과값이 /public~ 으로 시작하는 것 같은데요, 서버의 주소부터 해서 전체가 다 나오는건 어떨까요?
<img width="680" alt="image" src="https://github.com/team0102/weather-backend/assets/52498558/fe52ccaf-b262-46c9-8af8-dde575e182ee">

그렇게 하면 프론트에서 사용 할 때 혼동이 없을 것 같습니다.
나중에 서버 변경 등이 있을 때에도 문제가 적을 것 같고요~

2024-02-25 07:14 UTC, heyw00 commented on src/feed/feed.service.ts
> +            imageUrl : `/${FEED_PUBLIC_IMAGE_PATH}/${imageUrl}`,
테스트 할 때 편하도록 프론트에서 바꿔가며 get 하는 걸 생각했었어요! .evn 파일에 서버 url을 추가하도록 변경해봤습니다

2024-02-25 13:29 UTC, JISUlicious approved these changes

2024-02-26 03:55 UTC, Park-KJ approved these changes

2024-02-27 11:32 UTC, merged